### ISSUE TITLE
[UI] Rebrand Web Wallet to Flash - Bounty #1

### ISSUE THREAD

**Issue by islandbitcoin** [lnflash/web-wallet#1]
## Task:
Rebrand entire web wallet to be branded and themed for Flash. 

- [ ] Replace all blink images with flash images
- [ ] Replace all galoy text (Blink, BBW, Bitcoin Beach Wallet, Galoy, etc) to Flash
- [ ] Modify color scheme to match flash color scheme 

Bounty details posted [HERE](https://community.sphinx.chat/tickets)

**Comment by YLeight** [comment]
Hi @islandbitcoin. There are some issues with the first launching. Seems like extra steps needed for running locally.
Could you help with it?

**Comment by islandbitcoin** [comment]
ok let me try and launch it and then post instructions here
